# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/block_chain.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/block_chain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as proto_dot_common__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/block_chain.proto\x12\x05proto\x1a\x12proto/common.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xae\x01\n\x05\x42lock\x12\r\n\x05index\x18\x01 \x01(\x01\x12\x0c\n\x04hash\x18\x02 \x01(\t\x12\x15\n\rprevious_hash\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\x12\x13\n\x0bmerkle_root\x18\x05 \x01(\t\x12\x34\n\x13\x66ile_audit_requests\x18\x06 \x03(\x0b\x32\x17.proto.FileAuditRequest\x12\x13\n\x0b\x66ile_audits\x18\x07 \x03(\t\"0\n\x0fWhisperResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"0\n\x0fProposeResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"0\n\x0fGenesisResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xc9\x01\n\x11\x42lockChainService\x12\x45\n\x12wisperAuditRequest\x12\x17.proto.FileAuditRequest\x1a\x16.proto.WhisperResponse\x12\x34\n\x0cproposeBlock\x12\x0c.proto.Block\x1a\x16.proto.ProposeResponse\x12\x37\n\x0fgetGenesisBlock\x12\x16.google.protobuf.Empty\x1a\x0c.proto.Blockb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.block_chain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLOCK']._serialized_start=84
  _globals['_BLOCK']._serialized_end=258
  _globals['_WHISPERRESPONSE']._serialized_start=260
  _globals['_WHISPERRESPONSE']._serialized_end=308
  _globals['_PROPOSERESPONSE']._serialized_start=310
  _globals['_PROPOSERESPONSE']._serialized_end=358
  _globals['_GENESISRESPONSE']._serialized_start=360
  _globals['_GENESISRESPONSE']._serialized_end=408
  _globals['_BLOCKCHAINSERVICE']._serialized_start=411
  _globals['_BLOCKCHAINSERVICE']._serialized_end=612
# @@protoc_insertion_point(module_scope)
