# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import block_chain_pb2 as proto_dot_block__chain__pb2
from proto import common_pb2 as proto_dot_common__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/block_chain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BlockChainServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WisperAuditRequest = channel.unary_unary(
                '/proto.BlockChainService/WisperAuditRequest',
                request_serializer=proto_dot_common__pb2.FileAuditRequest.SerializeToString,
                response_deserializer=proto_dot_block__chain__pb2.WhisperResponse.FromString,
                _registered_method=True)
        self.ProposeBlock = channel.unary_unary(
                '/proto.BlockChainService/ProposeBlock',
                request_serializer=proto_dot_block__chain__pb2.Block.SerializeToString,
                response_deserializer=proto_dot_block__chain__pb2.ProposeResponse.FromString,
                _registered_method=True)


class BlockChainServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WisperAuditRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProposeBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlockChainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WisperAuditRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.WisperAuditRequest,
                    request_deserializer=proto_dot_common__pb2.FileAuditRequest.FromString,
                    response_serializer=proto_dot_block__chain__pb2.WhisperResponse.SerializeToString,
            ),
            'ProposeBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.ProposeBlock,
                    request_deserializer=proto_dot_block__chain__pb2.Block.FromString,
                    response_serializer=proto_dot_block__chain__pb2.ProposeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.BlockChainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.BlockChainService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BlockChainService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WisperAuditRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.BlockChainService/WisperAuditRequest',
            proto_dot_common__pb2.FileAuditRequest.SerializeToString,
            proto_dot_block__chain__pb2.WhisperResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProposeBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.BlockChainService/ProposeBlock',
            proto_dot_block__chain__pb2.Block.SerializeToString,
            proto_dot_block__chain__pb2.ProposeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
