# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/common.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/common.proto\x12\x05proto\"V\n\tAuditInfo\x12\x10\n\x08\x61udit_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12&\n\x0b\x61\x63\x63\x65ss_type\x18\x03 \x01(\x0e\x32\x11.proto.AccessType\"p\n\x10\x46ileAuditRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12$\n\naudit_info\x18\x02 \x01(\x0b\x32\x10.proto.AuditInfo\x12\x11\n\tsignature\x18\x03 \x01(\t\x12\x12\n\npublic_key\x18\x04 \x01(\t*F\n\nAccessType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04READ\x10\x01\x12\t\n\x05WRITE\x10\x02\x12\n\n\x06UPDATE\x10\x03\x12\n\n\x06\x44\x45LETE\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCESSTYPE']._serialized_start=231
  _globals['_ACCESSTYPE']._serialized_end=301
  _globals['_AUDITINFO']._serialized_start=29
  _globals['_AUDITINFO']._serialized_end=115
  _globals['_FILEAUDITREQUEST']._serialized_start=117
  _globals['_FILEAUDITREQUEST']._serialized_end=229
# @@protoc_insertion_point(module_scope)
